[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "{{cookiecutter.project_name}}"
version = "0.0.1"
dependencies = [
    "click",
]

[project.scripts]
til = "{{cookiecutter.project_slug}}:cli"
